### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yujiseok** [JIandBabies/vin-co#4]
### 클라이언트

---

- 로그인 기능 구현
  - [x] 전역으로 관리 어떻게 할지?
 <br/>

- 회원가입 기능 구현
  - [x] 전역으로 관리 어떻게 할지
  - [x] 프로필 이미지 잘 가져와지는 지 테스트 하기
 <br/>

- [x] 스타일 다듬기

<br/>

### 관리자 페이지
---

- 제품 수정
  - [x] 수정
  - [x] 삭제
 <br/>
